apiVersion: v1
kind: Namespace
metadata:
  name: instana-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-agent-operator
  namespace: instana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instana-agent-operator
  namespace: instana-agent
rules:
  # TODO: These are more rights than needed. Need to strip this down and should add
  # a comment on each one why it is needed.
- apiGroups: ["", "apps", "extensions", "rbac.authorization.k8s.io"] # "" indicates the core API group
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - replicasets
  - deployments
  - daemonsets
  - clusterroles
  - clusterrolebindings
  - serviceaccounts
  verbs:
  - '*'
- apiGroups: ["apiextensions.k8s.io", "customresourcedefinitions.apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups: ["agent.instana.io"]
  resources:
  - electedleaders
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instana-agent-operator
  namespace: instana-agent
subjects:
- kind: ServiceAccount
  name: instana-agent-operator
  namespace: instana-agent
roleRef:
  kind: ClusterRole
  name: instana-agent-operator
  apiGroup: rbac.authorization.k8s.io
