# kind --config kind-config.yaml create cluster
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /hosthome
      hostPath: /home
- role: worker
  extraMounts:
    - containerPath: /hosthome
      hostPath: /home
- role: worker
  extraMounts:
    - containerPath: /hosthome
      hostPath: /home
