apiVersion: v1
kind: Secret
metadata:
  name: instana-agent
  namespace: placeholder
  ownerReferences:
    - apiVersion: apps/v1
      kind: InstanaAgent
      name: placeholder
      uid: placeholder
type: Opaque
data:
  key: placeholder
