version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11

    steps:
    - checkout

    - restore_cache:
        keys:
          - m2-{{ checksum "pom.xml" }}
          - m2-

    - run: ./mvnw package

    - setup_remote_docker:
        version: 18.06.0-ce
        docker_layer_caching: true

    - run: docker build -f src/main/docker/Dockerfile.jvm .

    - save_cache:
        key: m2-{{ checksum "pom.xml" }}
        paths:
          - ~/.m2

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/