apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: instana-agent
data:
  agent.key: {{ put your Instana agent key here }}
  agent.endpoint: {{ the monitoring ingress endpoint }}
  agent.endpoint.port: {{ the monitoring ingress endpoint port, wrapped in quotes }}
  zone.name: {{ (optional) name of the zone of the host }}
