apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: instana-agent
data:
  zone.name: my-k8s-cluster
  agent.key: _PUT_YOUR_AGENT_KEY_HERE_
  agent.endpoint: saas-us-west-2.instana.io
  agent.endpoint.port: "444"
