apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: electedleaders.agent.instana.io
  namespace: instana-agent
spec:
  group: agent.instana.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: electedleaders
    singular: electedleader
    kind: ElectedLeader
    shortNames:
    - el
