apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-agent-operator
  namespace: instana-agent
spec:
  selector:
    matchLabels:
      app: instana-agent-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: instana-agent-operator
    spec:
      serviceAccountName: instana-agent-operator
      containers:
      - image: instana/instana-agent-operator
        name: instana-agent-operator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
